# Generated by Django 6.0 on 2026-01-02 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0002_social_link_alter_about_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Social_Link',
            new_name='Social_Media',
        ),
    ]
