# Generated by Django 6.0 on 2025-12-26 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0002_alter_category_options_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='blog_body',
            field=models.TextField(default=None, max_length=10000),
        ),
        migrations.AlterField(
            model_name='blog',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=100),
        ),
    ]
